### ISSUE TITLE
Centre colum of the page shifts slightly left when opening the "..." menu on posts

### ISSUE THREAD

**Issue by RetroSunstar** [bluesky-social/social-app#5734] opened 2024-10-12 01:22 UTC
### Steps to Reproduce

Click "..." on any post, whether it's on a user's profile, in a feed or a list

This causes parts of the page to shift left slightly while the menu is open

### What platform(s) does this occur on?

Web (Desktop)

### What version of the app are you using?

Build version: 1.92.0; Bundle info: 3b44ea2 (prod); Bundle date: 24101017; Platform: web

**Comment by surfdude29** [comment] 2024-10-12 01:44
This looks like a duplicate of #5681, which has been fixed on main and will be fixed when 1.92.1 is released soon.

**Closed** 2024-10-12 01:55 UTC
Labels: bug
