### ISSUE TITLE
PR #5898 breaks React Compiler optimization

### ISSUE THREAD

**Issue by shovel-kun** [bluesky-social/social-app#6025] opened 2024-10-31 01:54 UTC
### Steps to Reproduce

1. checkout [1fc684aaef6dd851b4d6c9a23673fcf4e7170722](https://github.com/bluesky-social/social-app/commit/1fc684aaef6dd851b4d6c9a23673fcf4e7170722)
2. install deps, build, and run Bluesky
3. `Shift+M` in terminal, choose `Open React devtools`
4. Notice that there are no `Forget` or ✨ badges
5. checkout commit https://github.com/bluesky-social/social-app/commit/a22685c34542d43a71c3496df28e86207ec7fbed, which is the commit before [1fc684aaef6dd851b4d6c9a23673fcf4e7170722](https://github.com/bluesky-social/social-app/commit/1fc684aaef6dd851b4d6c9a23673fcf4e7170722)
6. repeat 3&4
7. Notice that there are `Forget` badges

### Attachments

# Actual 
![2024-10-31T09:27:21,247721179+08:00](https://github.com/user-attachments/assets/9e3509d4-d594-4bf4-8b2c-caa759a7c95a)

# Expected (notice `Forget` badges)
![2024-10-31T09:23:15,936284922+08:00](https://github.com/user-attachments/assets/bd03b106-0498-47d7-83c2-9af48e508d76)

### What platform(s) does this occur on?

Android

### What version of the app are you using?

1.94.0

### Additional Information

#5898 uses `react-compiler-runtime@beta` for compiling  & optimization the React codebase instead of handrolling one from `lib/react-compiler-runtime`, as was done previously.

According to [React Compiler docs](https://react.dev/learn/react-compiler#how-do-i-know-my-components-have-been-optimized):

> [React Devtools](https://react.dev/learn/react-developer-tools) (v5.0+) has built-in support for React Compiler and will display a “Memo ✨” badge next to components that have been optimized by the compiler.

I've tried to check if the badge is present as stated in the reproduction steps above. However, there are no badges if I build and run the app after #5898 (see attached images).

**NOTE**: Perhaps there aren't any badges after #5898 because React Devtool used currently by Bluesky is on v4, whereas the docs states React Devtool expects v5.0+. However, prior to #5898 a `Forget` badge still shows even on v4. Further confirmation is needed to show that no badges appear even on React Devtool v5.0+.

BTW, the reason I brought this up is because I also wanted to use the react compiler for my app, and used the Bluesky's `lib/react-compiler-runtime` old method of doing it. However after switching to using `react-compiler-runtime@beta` from npm, the badges no longer appear in React Devtool. So I'm wondering if Bluesky is facing the same issue as I am, which seems to be the case.

**Comment by poteto** [comment] 2024-10-31 15:58
> React Devtool used currently by Bluesky is on v4

@shovel-kun could you share more about what you meant by this? I don't believe that Bluesky includes a bundled RDT anywhere, so is this more that your extension is outdated and needs updating?

For example, inspecting Bluesky Web does show the correct memo badges for me

![Screenshot 2024-10-31 at 11 58 08 AM](https://github.com/user-attachments/assets/79cd28bc-b367-432a-b9df-3e12e298bc6f)

**Comment by mozzius** [comment] 2024-10-31 16:26
I can confirm the memo badges are not present on https://main.bsky.dev. Thanks for spotting this, will look into it

**Comment by poteto** [comment] 2024-10-31 16:34
@mozzius If I'm not wrong this might be because of an outdated version of RDT. I still see the badges on main.bsky.dev. 

I made a small change to react-compiler-runtime a few weeks ago that busted the badging, but it was fixed in https://github.com/facebook/react/pull/31196 which should be released in [6.0.1](https://github.com/facebook/react/pull/31263)

**Comment by gaearon** [comment] 2024-10-31 16:34
https://main.bsky.dev/static/js/main.71ce8180.js seems to be compiled

<img width="750" alt="Screenshot 2024-10-31 at 16 32 08" src="https://github.com/user-attachments/assets/76efcd4f-13db-4e28-9a2d-b105f68670a7">

I also _do_ see the badges on `main.bsky.dev`

<img width="891" alt="Screenshot 2024-10-31 at 16 34 01" src="https://github.com/user-attachments/assets/799a6aba-1bd1-4a4a-a25a-cf1c53de58ca">

**Comment by mozzius** [comment] 2024-10-31 16:39
Yep, it's all good - I don't think 6.0.1 has been released to the Firefox extension store yet! Confirm it's fine in chrome

**Closed by mozzius** 2024-10-31 16:39 UTC
Labels: bug

**Comment by shovel-kun** [comment] 2024-10-31 16:43
Hi thanks for the response, 

I forgot to mention that I was testing if the React Compiler optimization was applying on Android, as mentioned in the reproduction steps above.

I can confirm that `Memo` badge appears on Bluesky Web though. Perhaps React Devtools for React Native Android/iOS is buggy? Could someone try and repro on Android/iOS?

**Comment by mozzius** [comment] 2024-10-31 16:47
As @poteto mentioned, old versions of RDT won't show the badges, and the version that React Native bundles is a little out of date. It should still be working, you can check the JS bundle output

**Comment by shovel-kun** [comment] 2024-10-31 16:51
Makes sense, I checked a local instance of Bluesky Web on Chrome and badges show, but not on Firefox.

Sorry for the wrong report, and thanks for helping.

**Comment by mozzius** [comment] 2024-10-31 16:56
No worries, thank you for raising it! I double checked iOS and the symbol is present, so all is good

![Screenshot 2024-10-31 at 16 55 34](https://github.com/user-attachments/assets/d77205e2-db20-4497-8584-2e9508f4090b)
