### ISSUE TITLE
[Web] Users sometimes taken back to previous URL (or blank page) when clicking some links

### ISSUE THREAD

**Issue by ichthyos** [bluesky-social/social-app#710] opened 2023-05-17 16:12 UTC
**Describe the bug**

Intermittently, clicking on Home or Profile makes the browser leave bluesky and navigate to the page that my browser was on before bluesky.

**To Reproduce**

Steps to reproduce the behavior are unclear, but I experience the bug after clicking on Home or Profile in the navigation on the left hand side.

**Expected behavior**

I would be taken to the appropriate page in bluesky.

**Screenshots**

N/A

**Details**

 - Platform: Desktop Chrome Windows
 - Platform version: Version 113.0.5672.93 (Official Build) (64-bit)
 - App version: Latest at https://staging.bsky.app/

**Additional context**

Not sure whether navigation to other pages (Search, Notifications, Moderation, Settings) are affected by the same bug.

**Comment by TheUnlocked** [comment] 2023-06-16 00:54
It feels like the history is being improperly memoized somehow. Try the following steps and print out `history.state.id` in the console beforehand and after pressing each button.

E.g.:
1. Home -> Search -> My Feeds -> Notifications -> My Feeds
2. Press back, goes to search (_not_ notifications)
3. Press back, goes to home

`history.state` is managed by `react-navigation`, so it's possible this is an upstream issue, or it could just be some subtle bug with how bluesky invokes `react-navigation`.

**Comment by tinymoons-dev** [comment] 2023-07-05 22:47
I've experienced the same issue, but I can't reliably reproduce the behavior.

Windows, Chrome Version 114.0.5735.199 (Official Build) (64-bit)

**Comment by estrattonbailey** [comment] 2023-08-15 21:27
Update: we're aware this is an issue but have been unable to reproduce as of yet. We'll keep this issue open and in the backs of our minds until we're able to figure out what's causing this 👍

**Comment by Zero3K** [comment] 2023-08-25 18:06
I am able to replicate it. Pressing Shift + F5 causes the page to show properly.

**Comment by ansh** [comment] 2023-09-11 08:04
@Zero3K Can you please provide reproduction steps?

**Comment by Zero3K** [comment] 2023-09-11 12:34
I do not know how I got it to happen.

**Comment by deceptionagent** [comment] 2024-02-14 09:56
i can reproduce this on demand in Safari on macOS:

1. open a new blank browser window.
2. enter google.com into the address bar and go. (any non-bsky.app site is fine, you just need a backstop in the history that will demonstrate the bug.)
3. go to http://bsky.app
4. click Notifications
5. click any notification
6. click the browser's back button
7. click that notification again
8. click the reply button on the single-post page that loads
9. click Cancel in the reply panel
10. click Home

--> your browser will now jump back to your backstop page.

**Comment by Bossett** [comment] 2024-02-14 09:59
reproduces as described on Chrome 121 (Win 11)

**Comment by mozzius** [comment] 2024-02-14 10:41
can reproduce on Firefox 122.0.1 (macOS Sonoma)

**Comment by mozzius** [comment] 2024-02-14 10:47
Seems opening the composer is not necessary - you can skip steps 8 and 9.

I can also reproduce going google -> bsky.app -> search -> profile -> back -> profile -> home

**Comment by deceptionagent** [comment] 2024-02-14 10:53
yeah i'm betting there are several ways to get here. i only spent a few minutes attempting to reduce it further.

i had tried a version without the composer and the bug didn't reproduce. i must have made a mistake while trying to reduce it. oops. :)

**Comment by gaearon** [comment] 2024-02-14 11:42
Fantastic, thank you for the repros. This should make it a lot easier to diagnose. Anyone wants to dig into the source?

**Comment by SlickDomique** [comment] 2024-02-14 12:30
You don't have to search at all. bsky -> any page -> back -> any other page -> home also triggers it

Weirdly enough this is not triggering any navigation events, only beforeunload gets triggered when this happens

**Comment by mozzius** [comment] 2024-02-14 15:05
I can replicate this on other react navigation sites (for example https://evanbacon.dev )

**Comment by SlickDomique** [comment] 2024-02-14 17:24
It's happening somewhere in or after batchedUpdates in react-dom

**Comment by SlickDomique** [comment] 2024-02-18 15:58
I further described the bug and have submitted potential fix to the react-navigation repository. The linked issue contains very simple repo with this issue replicated and a video showing the problem.

https://github.com/react-navigation/react-navigation/issues/11832

**Comment by haileyok** [comment] 2024-02-21 19:21
@SlickDomique Thank you! Applying your patch for now while we wait for it to get merged in. Thanks for digging into it!!

**Closed** 2024-02-22 01:54 UTC
Labels: bug, repro-needed, x:planned
