### ISSUE TITLE
Appealing labels removes self-labels

### ISSUE THREAD

**Issue by Bossett** [bluesky-social/social-app#3871] opened 2024-05-05 19:39 UTC
**Describe the bug**
When a user self-labels a post, it is then moderated by the official service. If the official service and the user use the same label shortname, and the user appeals it, it effectively removes *both* labels - completely unlabelling the post.

This is a significant issue as the two labels appear to be different in the UI (see #3870) - and operate differently in terms of user expectation.

**To Reproduce**

1. Make a self-labelled post
2. Wait for the AI moderation to label it
3. Appeal the label successfully
4. The post is no longer labelled at all

**Expected behavior**

Appealing a label from the official service should not negate the label already on the content - it should have the effect of reverting to the self-label.

**Comment by haileyok** [comment] 2024-05-05 22:37
Seems like this part of the problem isn't actually caused by the label being removed, but by the fact that you can't actually see a self label. 

In this case the situation looks like this:

- You post an image and add the self-label nudity
- The post gets upgraded to the porn label immediately. To the user, this Bluesky upgraded label appears to be their self label
- If the user realizes that the label was upgraded, they appeal the upgrade
- Bluesky moderation accepts the appeal, and downgrades it back to nudity
- To the poster, the UI makes it look like all labels were removed from their post, even though they were not.

This should adjust that behavior so more tweaks can be made. https://github.com/bluesky-social/atproto/pull/2467

**Comment by Bossett** [comment] 2024-05-05 22:45
Ooooh - I misunderstood the pattern, yes that looks like it solves.

Would that then re-use the 'X labels has been applied...' pattern?

**Comment by haileyok** [comment] 2024-05-05 22:46
Needs a separate fix, but yea that's ideal. Even with this fix you still wouldn't see the label if you had the setting to "Show" so need to add the little indicator.

**Comment by haileyok** [comment] 2024-05-05 22:47
I linked the PR so it will close when it gets merged.

**Comment by haileyok** [comment] 2024-05-06 05:16
Part two is here: https://github.com/bluesky-social/social-app/pull/3874

**Closed** 2024-05-09 01:42 UTC
Labels: bug
