### ISSUE TITLE
Mention link on profile screen

### ISSUE THREAD

**Issue by myConsciousness** [bluesky-social/social-app#1286] opened 2023-08-26 09:18 UTC
**Describe the bug**

There has been a minor bug in the profile screen for some time. 

For example, if you press the `Profile` menu from the web and go to the Profile screen, the Mention link in the description set in the profile is functional as shown in the following image.

<img width="584" alt="スクリーンショット 2023-08-26 18 05 26" src="https://github.com/bluesky-social/social-app/assets/13072231/cdccca7c-225e-41e1-aeed-ce1e94e091a8">

But if you transition from a link that was mentions in someone's post, the link is not set in the mentions as shown below.

<img width="585" alt="スクリーンショット 2023-08-26 18 06 12" src="https://github.com/bluesky-social/social-app/assets/13072231/d52a802b-9127-44ef-96af-075712053a20">

**To Reproduce**

## Web

1. Set up a Mention link in the Profile description
2. Transition to your profile screen from a post where someone mentions you

## Mobile

1. Set up a Mention link in the Profile description
2. Transition to your profile screen from a post where someone mentions you
3. Or swipe to update on your profile screen

**Expected behavior**

In any case, the Mention link in the profile description should be valid.

**Details**

 - App version:
   - `1.47.0`

**Additional context**

**Comment by myConsciousness** [comment] 2023-08-26 10:00
I haven't checked the code, but it may be that the process of setting the link to the mentions is not working depending on the route taken to the profile screen.

**Comment by intrnl** [comment] 2023-08-26 13:59
seems to be a dupe of https://github.com/bluesky-social/social-app/issues/1223#issuecomment-1686592904

**Comment by myConsciousness** [comment] 2023-08-26 15:31
@intrnl 

I read the Issue you shared, and I'm not sure if it's the same cause. But I imagine it's simply that the process of setting up the Mention link is missing only for certain routes.

**Comment by pfrazee** [comment] 2023-08-28 19:57
Yeah this is a dupe issue. You're right that something seems to cause it depending on the route taken to show the profile; I haven't been able to isolate the cause yet.

**Closed by pfrazee** 2023-08-28 19:57 UTC
Labels: bug, x:planned
