### ISSUE TITLE
Tapping Home icon goes to Help page with increased text size [accessibility, a11y]

### ISSUE THREAD

**Issue by ashleemboyer** [bluesky-social/social-app#1306] opened 2023-08-28 15:12 UTC
**Describe the bug**

When using increased text size on mobile, tapping the Home icon at the bottom left of the screen goes to the same place as the Help link that's at the bottom of the lefthand drawer.

**To Reproduce**

Steps to reproduce the behavior _in iOS_:

1. Go to Settings > Accessibility > Display & Text Size > Larger Text
2. Toggle on "Larger Accessibility Sizes"
3. Drag the text size setting all the way to the right
4. Open the Bluesky app
5. Tap the Home icon
6. Observe that you're taken to the Help page in the browser app

**Expected behavior**

I would expect tapping the Home icon to only activate that element. This issue make it impossible for users to go back to the Home page without closing and re-opening the app.

**Screenshots**

Here's a screen recording showing the behavior from my device (details in next section):

https://github.com/bluesky-social/social-app/assets/43934258/f45657e7-4687-4f13-996c-410ec838e332

**Details**

 - Platform: iOS
 - Platform version: iPhone 14 Pro Max / iOS 16.2
 - App version: "1.47.0 (3) production"

**Additional context**

- Fixing #1297 would provide a workaround for users since there is a Home `MenuItem` in the navigation drawer. But since that bug is also connected to increased text sizes, these issues compound each other.
- From my experience, I imagine the Drawer content isn't properly being hidden from the screen both visually and functionally. I've seen this happen in Web with combinations of `position: absolute` and `display: none`, but not sure how this gets translated to mobile by Expo. So far, I haven't been able to reproduce this issue in web.

**Comment by estrattonbailey** [comment] 2023-09-15 21:30
Hey! Apologies for the delay here.

Have you checked this recently, by chance? I'm not able to reproduce anymore, though I'm unsure what might have changed to make that so. Your recording is very clear, we def don't want that to happen. Thanks for providing it!

There's a lot we can do to improve our handling of font scaling, appreciate you helping us by reporting 👍

**Comment by ashleemboyer** [comment] 2023-09-15 21:40
No worries! I’ll see if the behavior still exists tomorrow, and will let you know. ☺️

**Comment by estrattonbailey** [comment] 2023-09-15 21:41
Oh ya know what, in testing #1297 I reproduced this. Working on fixing both now 👍

**Comment by estrattonbailey** [comment] 2023-09-27 16:10
Hey @ashleemboyer! I believe this issue is fixed in our latest release, v1.51. Thanks again for reporting!

**Closed by estrattonbailey** 2023-09-27 16:10 UTC
Labels: bug, x:planned
