### ISSUE TITLE
Users with many LISTS manifest a display issue on web and iOS app

### ISSUE THREAD

**Issue by sudoWright** [bluesky-social/social-app#2685] opened 2024-01-30 17:59 UTC
**Describe the bug**
1. User-created LISTS do not display or function as intended on the Bluesky 1.66 iOS app [(iPhone14Pro/iOS 17.3 (21D50)]
2. User-created LISTS display issue on the web-app version [Firefox 122.0/macOS 14.2.1 (23C71)]

Problem: I have created 17 lists covering various topics of interest to me. However, when viewing my profile in the Bluesky iOS app, I cannot scroll past the twelfth item on my LISTS. Similarly, when attempting to add a Bluesky user to my LISTS on the Bluesky website via my laptop, the view does not scroll, and you cannot add people to LISTS past the view it displays. 

**To Reproduce**

**- Bluesky iOS app 1.66 on iPhone:**
1. Install Bluesky for iOS 1.66
2. Open and sign in to the Bluesky account
3. Open my profile (https://bsky.app/profile/sudojames.com) and select "LISTS"
4. Scroll down on the LISTS; you will see it cuts off the list and stops at twelve.

**- Bluesky web app on Firefox via macOS:** 
1. Open Firefox on a Macbook and navigate to https://bsky.app
2. Sign into the platform
3. From any user profile, select (...) and then "Add to Lists."
4. When the dialog box opens- the LISTS do not scroll and cutoff so a selection is impossible. 

**Expected behavior**

I should be able to scroll all my user-created LISTS without having the display cutoff. I can add and remove people from my LISTS as a workaround using the third-party 'deck.blue.' 

**Screenshots**

You can see in this screenshot that in the Bluesky iOS app, users with many LISTS do not scroll. 
![iOS_LISTS](https://github.com/bluesky-social/social-app/assets/25876554/f2c67414-d74e-4382-8a07-979b81202003)

You can see in this screenshot that in the Bluesky web app, users with many LISTS do not scroll to add folks.
![web_LISTS](https://github.com/bluesky-social/social-app/assets/25876554/6088bb3a-a9da-40ff-92a8-178f30055c01)

**Comment by surfdude29** [comment] 2024-01-31 02:17
I think the bug on the web is a dupe of #2674 which is fixed by #2678

**Comment by haileyok** [comment] 2024-01-31 02:18
Yup, #2678 also fixes the issue on ios and android 👍 thanks @surfdude29

**Closed by haileyok** 2024-01-31 02:18 UTC
Labels: bug
