### ISSUE TITLE
Text Breaks in New Post Button on Desktop

### ISSUE THREAD

**Issue by trozzelle** [bluesky-social/social-app#628] opened 2023-05-15 21:30 UTC
**Describe the bug**
The 'New Post' button text wraps in Firefox Desktop on macOS, creating a two-line button.

**To Reproduce**

1. View staging.bsky.app in Firefox browser (build 113.0.1) on macOS. 

**Expected behavior**

The text should not wrap.

**Screenshots**

![Bluesky Text Overflow](https://imperativeny.s3.amazonaws.com/Screenshot+2023-05-15+at+5.11.18+PM.png)

**Details**

macOS 13.3.1, Firefox build 113.0.1 (unlikely to be build specific)

**Additional context**

The button wraps because the way Firefox implements the OpenType spec for variable-size fonts creates thicker text for font-weight ("bold") than other browsers. For the macOS system font, this creates a div width of 79px vs 77.02 for Safari and Chrome. This difference also exists on Windows 11 desktop but the width difference for Segoe UI is only ~0.5 px at font-weight 700. 

This can be solved be increasing the newPostBtn width from 138px to 140px in LeftNav.tsx but would still be susceptible to breaking incorrectly on a non-standard system font or if the browser base text size is greater than 16px. A more permanent solution would be using responsive units, like em which would scale with the size of the countaining element.

**Comment by alimony** [comment] 2023-05-16 11:42
This affects more than just the new post buttons, see for example the top-right links:

<img width="310" alt="Screenshot 2023-05-16 at 13 38 54" src="https://github.com/bluesky-social/social-app/assets/331091/08ac508d-dd9d-49e4-beac-7154366b3524">

In fact, you can toggle between various sets of system fonts in the inspector on Firefox and Chrome to see things jump around in general. I think GitHub uses the same font stack and doesn't have this issue, so that could be a clue.

**Comment by deviant-semicolon** [comment] 2023-05-16 13:10
I've noticed this issue with alt text on mobile. The alt text button ends up looking like:

AL
T

**Comment by zcorpan** [comment] 2023-05-16 13:40
> The button wraps because the way Firefox implements the OpenType spec for variable-size fonts creates thicker text for font-weight ("bold") than other browsers. For the macOS system font, this creates a div width of 79px vs 77.02 for Safari and Chrome. This difference also exists on Windows 11 desktop but the width difference for Segoe UI is only ~0.5 px at font-weight 700.

Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1833392

**Comment by renahlee** [comment] 2023-05-16 18:59
@deviant-semicolon ALT should be fixed in https://github.com/bluesky-social/social-app/pull/618. If the issue persists after release, please let us know!

**Comment by ansh** [comment] 2023-09-05 23:19
I am unable to reproduce this bug. @trozzelle Is it still an issue? I have tried with your specific Firefox version. If you have changed the font sizing via macOS system settings please let me know.

**Closed** 2024-10-08 23:32 UTC
Labels: bug, x:planned
