### ISSUE TITLE
No Emails, Cannot Retrieve Password

### ISSUE THREAD

**Issue by Mike-E-angelo** [bluesky-social/social-app#965] opened 2023-07-04 08:09 UTC
**Describe the bug**
Pardon if this is not the appropriate location for the report.  I have found no support channels for your product and this is the closest approximation.  Additionally, I feel I may have landed on a bug, so we'll see how we do here.

I signed up with an account, but received zero emails of the signup.  Additionally, when I use the send password form, no email is sent.

**To Reproduce**

I created an account 3 days ago but landed on the key/code required to create an account.  I left the browser open for 2 days and got a key on the third day (yesterday) and created the account.  At no time was any email sent and I have no email in any of my accounts from `bsky.social`

1. Open browser and go through sign up process until keycode is requested
2. Wait 2-3 days
3. Complete signin process  with code

**Expected behavior**

Email provided 2-3 days ago is remembered and account is created as expected with email sent as a notification.

**Screenshots**

NA

**Details**

 - Platform: Chrome
 - Platform version: Windows 10
 - App version: Web

**Additional context**

Everything else worked fine 😊

**Comment by pfrazee** [comment] 2023-07-05 20:08
Yeah the "account confirmation email" has been a long-standing todo. I'm going to close this as a duplicate of https://github.com/bluesky-social/atproto/issues/479

**Closed by pfrazee** 2023-07-05 20:08 UTC
Labels: bug

**Comment by Mike-E-angelo** [comment] 2023-07-05 20:14
Thank you @pfrazee I appreciate the pointer and have commented there.  It would be nice to get back into my account. :)

**Comment by Mike-E-angelo** [comment] 2023-07-06 07:35
Hi @pfrazee pardon the delay in realizing this, but the confirmation email is only one part of this.  The primary issue that I am encountering is that none of my email addresses are sending me the reset code to my account.  

My concern is that the email address is not assigned to the account if the create-account workflow is open for an extended period, losing the state of the account creation and not assigning an email to the account when it is created.  Does this make sense?  Is this a possible issue?

**Comment by pfrazee** [comment] 2023-07-06 17:13
Are you logged in? If so you can see your email in the settings page and confirm if it's wrong

**Comment by Mike-E-angelo** [comment] 2023-07-06 17:50
That's just the problem @pfrazee and the reason I ended up here.  I was logged in and then got logged out for some reason.  I did not log out deliberately, but the system did it for me.  I also realized that my password manager didn't save my password, either.  I then attempted to reset my password using all known emails to me and none of them sent a ping.

So unfortunately no, I am not logged in and I cannot find a way to log back in.  Due to none of my emails working, I have a feeling that my email did not get saved in your system due to the reproduction steps I originally reported in the ticket here.

Thank you for any further assistance/direction that you can provide.

**Comment by Mike-E-angelo** [comment] 2023-07-17 18:24
Hi @pfrazee I wanted to check in with this issue as I did not hear back from you.  Can you verify that you have tested the above scenario?  Please let me know if I should make another ticket/issue to better track.  Thank you for your continued consideration.

**Comment by pfrazee** [comment] 2023-07-17 21:21
Sorry @Mike-E-angelo, juggling a lot.

We basically don't have a great solution for incorrect emails right now. We've been solving it by directing people to email support@bsky.app and trying to find a way to confirm ownership. I hope they can clear it up for you

**Comment by Mike-E-angelo** [comment] 2023-07-17 21:24
No worries @pfrazee I appreciate your response.

The issue isn't incorrect emails, the issue is the stored state of the account creation.  So again from the report above:

1. Open browser and go through sign up process until keycode is requested
2. Wait 2-3 days
3. Complete signin process with code

Can you confirm the email is stored properly in step 1 so that when step 3 continues 2-3 days later the email/state is properly retrieved/resumed from step 1?
