### ISSUE TITLE
If someone in a thread blocks a user, the post is not visible for the author anymore. (Was: My post disappeared)

### ISSUE THREAD

**Issue by antont** [bluesky-social/social-app#1961] opened 2023-11-18 11:38 UTC
**Describe the bug**
A post I wrote yesterday is not accessible anymore. I see a notification about it, but trying to view the post shows "Post not found. The post may have been deleted". I did not delete it. I think I even got a later push notification about a reply to it, but that does not show in the in-app notifications.

**To Reproduce**

1. Post something to Bluesky

**Expected behavior**

Try to view the post and see it.

**Screenshots**

Post, the topmost one, shows in notifications:
![image](https://github.com/bluesky-social/social-app/assets/201016/ff59b53d-8bfa-4691-ae2d-5f82bc76023a)

If I open it, it flashes in view, I captured this to video so this is a frame from that:
![image](https://github.com/bluesky-social/social-app/assets/201016/92ed0f32-55d1-4271-9ed6-ae3b9baea1ac)

Finally Bluesky says post not found:
![image](https://github.com/bluesky-social/social-app/assets/201016/882cb9c2-b1d5-42d0-ba97-ff9632414e8b)

**Details**

 - Platform: I think I used the iOS app to post originally. The post does not show with browsers either.
 - Platform version: iOS 16.6.1
 - App version: 1.56.0

**Additional context**

I think I even got a later push notification about a reply to it, but that does not show in the in-app notifications.

**Comment by mackuba** [comment] 2023-11-20 01:17
It's another case of https://github.com/bluesky-social/atproto/issues/1387

**Comment by antont** [comment] 2023-11-20 08:34
> It's another case of [bluesky-social/atproto#1387](https://github.com/bluesky-social/atproto/issues/1387)

Yep I realized that too, when seeing some other part of the thread and seeing the block. Was in my todo to come update the bug report here, but also did not find previous one. Thanks! Maybe it's useful to have this mentioned in this repo too, edit the title first now but don't close.

**Comment by pfrazee** [comment] 2023-12-19 20:56
Closing as a duplicate of https://github.com/bluesky-social/social-app/issues/2243; this is being worked on

**Closed by pfrazee** 2023-12-19 20:56 UTC
Labels: bug
