### ISSUE TITLE
Video and GIF/Animation Support 

### ISSUE THREAD

**Issue by Kuroo2021** [bluesky-social/social-app#1643] opened 2023-10-09 06:00 UTC
**Is your feature request related to a problem? Please describe.**

Lack of video and/or GIF support on the BlueSky platform. 

**Describe the solution you'd like**

Coded so that animation and GIF are supported on the platform.

**Describe alternatives you've considered**

None

**Additional context**
None

**Comment by str4d** [comment] 2023-10-09 08:08
Duplicate of #1047 and #1052.

**Closed** 2023-10-09 19:26 UTC
Labels: x:duplicate, feature-request
