### ISSUE TITLE
Images on feed occasionally appear corrupted

### ISSUE THREAD

**Issue by HeyItsLollie** [bluesky-social/social-app#1761] opened 2023-10-27 06:45 UTC
![ApplicationFrameHost - 2023-10-27 - 16-42-02](https://github.com/bluesky-social/social-app/assets/30498581/c20cc16d-e0f2-4a9d-8541-bb3c7a488f5f)

It's difficult to know when or why I encounter this sort of image corruption on my feed, but I've been seeing it semi-regularly over the past week or two.

It appears to be server-side, possibly something to do with image delivery, because corrupted images on the feed can be fixed with a simple refresh, and they don't appear corrupted when viewed in Lightbox.

![ApplicationFrameHost - 2023-10-27 - 16-43-31](https://github.com/bluesky-social/social-app/assets/30498581/63ae5b94-1268-4bc0-9239-cf13f9ce0b6c)

This has been occurring in Firefox, Windows 11 Pro.

**Comment by pfrazee** [comment] 2023-10-27 16:51
bizarre! we'll have to find some time to look into it

**Comment by mozzius** [comment] 2023-11-01 13:59
@DavidBuchanan314 did some investigating, thread here:
https://bsky.app/profile/retr0.id/post/3kcaudsnbdu2x

**Comment by DavidBuchanan314** [comment] 2023-11-01 14:32
I'm fairly confident this is a firefox bug. I disabled HTTP/2, on a hunch, and it does seem to have fixed the issue for now because I haven't seen it since then.

**Comment by DavidBuchanan314** [comment] 2023-11-01 14:56
@HeyItsLollie how "stable" would you say your internet connection is? Do you connect wirelessly or wired?

Obviously issues like this shouldn't be happening regardless of connection quality, but I have a hunch that the issue is related to how firefox's network stack handles dropped packets, and how that subsystem interacts with progressive loading of jpegs.

**Comment by eliemichel** [comment] 2023-11-05 21:11
Experiencing this issue as well, right after I posted a message:
![image](https://github.com/bluesky-social/social-app/assets/5802849/b20d6e70-96f7-45f0-8a1c-0596c148c2cd)

Running Firefox indeed (on Windows), an error in the Browser console says about "Image corrupt or truncated.", and after a couple of seconds I reloaded and it got fixed. I use a reasonnably good wired connection I don't think it got interrupted during the process.

**Comment by DavidBuchanan314** [comment] 2023-11-05 23:53
This just happened to me again (I've since re-enabled HTTP2). Unfortunately I didn't have dev tools open at the time, but I did open them before clicking on the affected post.

Having clicked the post, the image loaded correctly this time (not even a full page refresh). However, the image wasn't loaded from the cache, it was actually re-requested. So, my earlier statements about the image arriving correctly in cache the first time weren't necessarily correct (I'd previously incorrectly assumed that firefox wasn't re-requesting the image).

Next time this happens, I'm gonna take a copy of firefox's cache and comb through it to see if I can find the affected file, before it gets replaced with a correct one.

**Comment by nagornyi** [comment] 2023-12-12 02:27
This happens for me too in Firefox (both Mac OS X and Linux), image corruption in the feed makes Bluesky almost unusable in this browser, I have to use Chrome to avoid this bug.

![Screenshot 2023-12-12 at 11-21-23 Bluesky Social](https://github.com/bluesky-social/social-app/assets/103919/a44bc693-00f3-4335-9bc2-f6005fcf7aa3)

![Screenshot 2023-12-12 at 11-23-22 Bluesky Social](https://github.com/bluesky-social/social-app/assets/103919/e88bb6b7-e7ec-436e-b72a-3e38b363cf6b)

**Comment by DavidBuchanan314** [comment] 2023-12-13 03:47
I'm able to consistently reproduce this now, for profile banner images the first time I view a new user's profile. Ridiculously, it never happens with dev tools open.

**Comment by DavidBuchanan314** [comment] 2023-12-13 04:02
[har.zip](https://github.com/bluesky-social/social-app/files/13655730/har.zip)

**Comment by DavidBuchanan314** [comment] 2023-12-13 04:11
I just set up SSLKEYLOGFILE+wireshark in an attempt to get a proper packet capture, but *of course*, I'm now unable to reproduce it again.

**Comment by pfrazee** [comment] 2023-12-13 05:49
dang @DavidBuchanan314. that's really detailed work

**Comment by pfrazee** [comment] 2023-12-19 19:37
@Jacob2161 I'm going to assign this to you, if you can keep folks updated I'd appreciate it!

**Comment by Jacob2161** [comment] 2023-12-19 20:37
Yeah thanks for this @DavidBuchanan314 we'll definitely look into it ASAP.

**Comment by Jacob2161** [comment] 2023-12-19 23:52
I can't reproduce this on `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0` but we were advised to try disabling request coalescing by our CDN provider, which I've done.

If anyone watching this issue is able to test whether this has resolved the issue or not, that'd be very helpful 🙏

**Comment by DavidBuchanan314** [comment] 2023-12-21 06:45
It does seem to have stopped happening, but it's always been fairly intermittent so hard to say if it's definitely fixed. I'll let you know if it shows up again.

**Comment by pfrazee** [comment] 2023-12-27 17:42
IIRC @Jacob2161 changed a setting on the CDN. Going to optimistically close.

**Closed by pfrazee** 2023-12-27 17:42 UTC
Labels: bug, x:planned
