### ISSUE TITLE
Non-user friendly error when feed is broken

### ISSUE THREAD

**Issue by fenarinarsa** [bluesky-social/social-app#1670] opened 2023-10-11 09:30 UTC
**Describe the bug**

Currently the Home+ custom feed from user memgraph.com is broken because of an invalide TLS certificate (it seems).

When the "Show Posts from My Feeds" exeperimental feature is checked, a loading error often pops up on the Following timeline because of this.

**To Reproduce**

1. Subscribe to Home+
2. Enable "Show Posts from My Feeds"
2. Scroll your Following feed

**Expected behavior**

The bluesky app either should ignore the error and don't show the posts, or embed the error as a post. If an error message is shown, the display name of the feed should be mentionned. (like "error loading posts from Home+ feed").
A way to easily unsubscribe the feed should also be provided, since there's no way to directly unsubscribe a broken feed (the only way is currently to find the feed's owner, go to the user account in the Feeds tab).

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/17545417/505a192f-21b9-456f-b663-a20f0bba7abc)

**Details**

 - Platform: Firefox
 - Platform version: Windows 118.0.1
 - App version: 1.5.2

**Comment by pfrazee** [comment] 2023-10-25 17:28
Closing as a duplicate of #1685

**Closed by pfrazee** 2023-10-25 17:28 UTC
Labels: bug
