### ISSUE TITLE
[Aesthetic] Convert Posts With a Single Hyperlink to Link Cards Automatically

### ISSUE THREAD

**Issue by MichaelGHUser** [bluesky-social/social-app#3056] opened 2024-02-29 20:01 UTC
**Describe the solution you'd like**

When users compose on Bluesky, posts can have both link cards and hyperlinks.  On posts with a single hyperlink, this is redundant.  If the hyperlink is automatically converted to a link card, it would do three things.  The link card would serve as visual confirmation that Bluesky is reasonably certain that the external link is not malicious.  Secondly, it will look better.  Finally, it will bring the platform more in-line with competitors.  Familiarity will entice more people to join.

**Comment by Zero3K** [comment] 2024-02-29 23:29
This is a duplicate of https://github.com/bluesky-social/social-app/issues/2321.

**Comment by MichaelGHUser** [comment] 2024-02-29 23:59
Thanks!

**Closed** 2024-02-29 23:58 UTC
Labels: feature-request
