### ISSUE TITLE
Web post composer can produce garbled text after inserting an emoji

### ISSUE THREAD

**Issue by intrnl** [bluesky-social/social-app#1300] opened 2023-08-28 07:07 UTC
**Describe the bug**

Inserting an emoji and them messing around with the post composer can cause the composer's text content to become garbled, emojis turning into `�` for example

**To Reproduce**

1. Open post composer
2. Insert an emoji from the emoji picker
3. Text input briefly focuses before blurring, so you try to focus again, but just before the emoji you just inserted
4. Press backspace after focusing.

**Expected behavior**

Nothing should be deleted as the cursor is on the first index.

**Screenshots**

[Kooha-2023-08-28-14-01-24.webm](https://github.com/bluesky-social/social-app/assets/20620901/96fc077a-4f28-49be-aa88-46b9bc823706)

**Details**

 - Platform: Desktop Firefox Linux 
 - Platform version: Firefox 118.0a1 (2023-08-27), Arch Linux 6.4.11-1-cachyos
 - App version: 1.47

**Additional context**

Not entirely sure what's currently happening, I'll dig around for causes

**Comment by intrnl** [comment] 2023-08-28 07:11
seems like this exclusively happens when messing around with the emoji specifically, you can see here how messing around with other parts of the text is unaffected, only when you happen to focus on *just before* the emoji and press backspace

[Kooha-2023-08-28-14-09-35.webm](https://github.com/bluesky-social/social-app/assets/20620901/8f57fc3f-6bdd-41bc-821d-229270e0cb6d)

**Comment by simonetthomas** [comment] 2023-08-28 09:47
It seems the emoji is made of two "parts", and when you add it and focus the composer again, the cursor appears in the middle of them. So when you press backspace, it deletes the left part and scrambles the emoji. When you add text immediately after focusing, the letters appear in the "middle" of the emoji (I don't know how emojis work technically)

https://github.com/bluesky-social/social-app/assets/36693311/11ffbcab-7f9d-405a-8339-d3ede489655f

**Comment by pfrazee** [comment] 2023-08-28 19:06
Now _that_ is an interesting behavior. Emojis are indeed made of multiple "parts", and it seems like tiptap (our web rich text editor) is in fact mispositioning the cursor into the middle of the emoji.

@gaearon I'm going to let you tackle this one; it looks like this might be a Firefox issue but we should check other browsers

**Comment by mschwendener** [comment] 2023-08-28 21:14
> looks like this might be a Firefox issue but we should check other browsers

Can reproduce in Firefox on Mac, not in Chrome or Safari. 

Position of the cursor is different after starting a post with an emoji via the emoji picker: 

Safari: 
places the cursor after the emoji

Chrome: 
I have to manually place the cursor into the post again (it's visible to the left of the emoji really quickly, but then disappears)

Firefox: 
I have to manually place the cursor into the post again (it's visible to the left of the emoji really quickly, but then disappears)

**Comment by simonetthomas** [comment] 2023-08-29 00:21
I just tried on Edge on Windows 10 and no issue. So it seems it affects mainly Firefox.

As a side note, picking a emoji should put the focus back in the post automatically, without having to click on the post again which is not convenient.

**Comment by mschwendener** [comment] 2023-08-29 16:48
> picking a emoji should put the focus back in the post automatically

That looks like it would even be the solution:
 
Firefox on Mac or Windows: I start a post with an emoji, manually place the cursor left of it, and backspace behaves as described in post 1.

But: If after picking the emoji I first manually place the cursor **after** it, and only then place the cursor directly left of the emoji, backspace has no unexpected effect.  

So if "place cursor after the emoji" could be forced, the bug would go away.

**Comment by gaearon** [comment] 2023-09-04 23:01
I've briefly looked at this. Our custom logic is suspicious — although there may be something on the tiptap side as well.

This line seems wrong in general (for all browsers):

https://github.com/bluesky-social/social-app/blob/419ac2d0df013db08bec0eb9cef8e6fd5a0bcd33/src/view/com/composer/text-input/TextInput.web.tsx#L149

It causes the emoji itself to *always* be inserted at the end of the input. However, the user might have opened the picker in the middle of the word. In that case, the expectation is that the emoji will be inserted where the caret was — not at the end. So this seems like it should be `focus()` rather than `focus('end')`.

Having fixed that, we'll notice that right after the emoji is inserted, the caret appears a wrong spot. (That might have been the motivation behind calling `focus('end')` above.) This appears to be due to this code:

https://github.com/bluesky-social/social-app/blob/419ac2d0df013db08bec0eb9cef8e6fd5a0bcd33/src/view/com/composer/text-input/TextInput.web.tsx#L114-L116

We're manually trying to move the caret to the end, but this `.length` read doesn't seem to give consistent results. E.g. when I add an emoji to an empty field, sometimes I get `0` and sometimes I get `2`. Maybe there's some kind of a timing issue, like the event firing before the change was flushed in some cases. Regardless, it seems a bit fragile to read `.length` in the middle of an editing transaction. I'm wondering if we can use `focus('end')` instead here which clarifies intent and hopefully don't suffer from similar issues. If I change this line to `e.chain().focus('end').run()`, the caret consistently moves to the end after the insertion. (This also consistently appears to solve the Firefox-specific issue in this thread.)

It still seems shady though that we'd always move the caret to the end on focus. I don't actually want that as a user if I'm inserting an emoji in the middle of the text. I want the caret to *stay* at the insertion point. Also, in general, if I blur the field and then click on it, I expect the caret to appear where I clicked — but this line of code is currently forcibly moving the caret to the end anyway.

So I think the fix should be to remove this line altogether. It was originally added in https://github.com/bluesky-social/social-app/commit/16b265a86164e682486a3d8fa51bfa18d51bb945 and I'm not super sure why so maybe removing it would regress on something. @ansh do you recall why it was necessary?

**Comment by gaearon** [comment] 2023-09-04 23:14
PR in https://github.com/bluesky-social/social-app/pull/1374.

**Closed** 2023-09-05 07:21 UTC
Labels: bug, x:planned
