### ISSUE TITLE
Visually inconsistant context menus on Web

### ISSUE THREAD

**Issue by mozzius** [bluesky-social/social-app#1154] opened 2023-08-11 17:46 UTC
A picture is worth a thousand words:

<img width="454" alt="Screenshot 2023-08-11 at 18 43 43" src="https://github.com/bluesky-social/social-app/assets/10959775/6a7ef651-076b-4e89-b622-44902711cdaa">
<img width="429" alt="Screenshot 2023-08-11 at 18 43 48" src="https://github.com/bluesky-social/social-app/assets/10959775/ea08859f-0e8b-4f1b-a94e-b205f48e6d98">

Seems the repost menu needs updating with the shiny new context menu component - probably got missed because it only uses the context menu on web.

Happy to make a PR

**Comment by ansh** [comment] 2023-08-14 04:06
Yeah this should be the new one for sure. Mobile shows a modal, which is a different behavior which we'd like to keep at the moment. Happy to accept a PR but I can prolly knock this out in 20 minutes if its too much of a hassle for ya!

**Comment by mozzius** [comment] 2023-09-13 12:12
Seems like the backdrop no longer shows:

<img width="644" alt="Screenshot 2023-09-13 at 13 10 12" src="https://github.com/bluesky-social/social-app/assets/10959775/5418540a-17ef-446f-afc0-14e942739c7d">

I had a go at making a PR but I couldn't figure out a neat way to do it - not sure where the best place to branch the logic for diplaying context menu items is

**Comment by ansh** [comment] 2023-09-13 12:40
@mozzius Sorry, which backdrop are you referring to?

**Comment by mozzius** [comment] 2023-09-13 12:43
The menu is open but the rest of the screen isn't darkened, so you can't see the menu's border at all (see screenshot)

**Comment by ansh** [comment] 2023-09-13 13:07
@mozzius Omg I couldn't even see the menu hahahha 

I am unable to reproduce this. This is web, right?

<img width="384" alt="CleanShot 2023-09-13 at 18 36 28@2x" src="https://github.com/bluesky-social/social-app/assets/8207733/89ede103-fc19-406b-90ba-e2fd7f507c97">

**Comment by mozzius** [comment] 2023-09-13 13:08
Yep, Firefox. Lemme see if I can reproduce

**Comment by mozzius** [comment] 2023-09-13 13:16
![Screenshot 2023-09-13 at 14 15 04](https://github.com/bluesky-social/social-app/assets/10959775/59a4be27-4606-4fa0-8895-fd41603293a3)

Firefox on a different MacBook - it gets even better because without the backdrop, you can select as many as you'd like! And you can keep scrolling to collect more!

**Comment by mozzius** [comment] 2023-09-13 13:16
Oh and they stick around even when you change tab

**Comment by pfrazee** [comment] 2023-09-13 14:43
We just pushed a fix to this, not yet released

**Closed** 2023-09-27 16:14 UTC
Labels: feature-request, x:planned
