### ISSUE TITLE
Many elements jump in Firefox on Linux.

### ISSUE THREAD

**Issue by opalapo** [bluesky-social/social-app#1593] opened 2023-10-03 21:52 UTC
**Describe the bug**

~~homeScreenFeedTabs raises and lowers rapidly~~ Most visible elements jump around as mouse scroll event triggers the issue.

Firefox shows multiple errors both ~~flickering~~ jumping and non jumping ~~flickering~~ with:
Error in parsing value for ‘aspect-ratio’.  Declaration dropped. 3 bsky.app:1:1

**To Reproduce**

1. scroll up and down on feed, issue is intermittent

sometimes the issue seems hidden yet still produces errors
sometimes ~~it flickers~ there is jumping when no more scroll events occur

**Expected behavior**

No continuous jumping of elements when scrolling stops. ~~flapping up and down of homeScreenFeedTabs~~

**Screenshots**

~~Can't make a video at moment.~~
I attached two videos, one github cant parse the codecs inside the container.
The 2nd embeds fine.

Filter on "aspect-ratio" and CSS in the inspector to watch happen when triggered.

**Details**

 - Platform: firefox
 - Platform version:  118.0.1 in linux
 - App version: main

**Additional context**

~~When I delete the 2nd 'translateY' from the CSS inspector panel, issue is resolved reduced.~~ I thought it was eliminated but the issue recurs.

https://github.com/search?q=repo%3Abluesky-social%2Fsocial-app+translateY%288px%29&type=code

https://github.com/bluesky-social/social-app/blame/fd5bbb27699942f7d741d074eafdf16bfc9ecdd6/web/index.html#L151

https://github.com/bluesky-social/social-app/assets/125841094/18dcc9d0-19bd-41bb-9131-ea43f0df1343

https://github.com/bluesky-social/social-app/assets/125841094/ba6ad519-ef3e-44f9-b1ae-43f9c4692a08

**Comment by pfrazee** [comment] 2023-10-04 17:39
I'm not able to reproduce this, and I wonder if this is either a graphics driver issue. That said, we could try a different way to do this css. Could you try this?

```css
      [data-tooltip]::after {
        content: attr(data-tooltip);
        display: none;
        position: absolute;
        bottom: -8px; /* CHANGED FROM 0 */
        left: 50%;
        transform: translateY(100%) translateX(-50%); /* DROPPED THE SECOND TRANSLATE */
        padding: 4px 10px;
        border-radius: 10px;
        background: var(--backgroundLight);
        color: var(--text);
        text-align: center;
        white-space: nowrap;
        font-size: 12px;
        z-index: 10;
      }
```

**Comment by opalapo** [comment] 2023-10-05 18:19
I tried your fix but didn't see results until also applying it to the 'before' data-tooltip as well. I will continue testing it today. To be fair, CSS reflow is terrible and glitchy so I don't expect a real fix. Gotta cover the most common scenarios bases and firefox on linux with all the variations is just gonna be a time waster. I appreciate you even picking this one up.

What I will say tho about this is: Why even use the small screen layout when my browser window is ~50% of a 1440p window? A bit bigger window activates a different layout where there isn't even a home screen feed tab but a sidebar of links instead.

![image](https://github.com/bluesky-social/social-app/assets/125841094/ed99d324-ad61-4e76-a82b-cf753cd67cfc)

**Comment by opalapo** [comment] 2023-10-07 19:31
I tested your suggested change on ::after and then on ::before and then both.
It did not resolve the issue.
This seems like an issue with how reflow is done/calculated in Firefox as most of the visible elements jump not just the home screen tab bar. I changed the ticket to reflect the bigger effect vs just the tab bar.

**Comment by fenarinarsa** [comment] 2023-10-10 13:10
For what its worth, I have the same kind of issue with Firefox on Windows.

**Comment by Potato22** [comment] 2023-10-15 11:18
I've also noticed the scrolling behavior can jump by itself too in Firefox Windows. Making a very unpleasant scrolling experience. I've sent a ticket about this already just now, but won't hurt to mention it again. - unless this is unrelated, which I can't be too sure.

**Comment by haileyok** [comment] 2024-03-09 05:15
I think all of this has been fixed with changes over the past months, but if there's anything you are still running into please feel free to open another issue 🙏

**Closed by haileyok** 2024-03-09 05:15 UTC
Labels: bug, x:discussing
