### ISSUE TITLE
Text goes outside of border on web app

### ISSUE THREAD

**Issue by okpierre** [bluesky-social/social-app#3906] opened 2024-05-08 01:32 UTC
Text goes outside of border on web app. See screenshot below

Red line is the border and circled the text that goes outside the border

1. Go to bsky.app
2. View feed
3. Some posts show text outside

**Expected behavior**

Text do not go beyond border

**Screenshots**

![bskywebborder](https://github.com/bluesky-social/social-app/assets/1679025/cd744bb0-45bb-4ea9-bb78-dd3d3a57ded5)

 - Platform: Ubuntu 22.04 / Firefox browser 123.0 (64 bit)

**Comment by mary-ext** [comment] 2024-05-10 02:50
Can't reproduce, long names overflow but it gets clipped. Tested on Firefox 125 and Firefox Nightly 127 (Arch Linux)

![image](https://github.com/bluesky-social/social-app/assets/148872143/1cec47ad-d583-4ff8-ad23-c7b89a12faec)

**Comment by mary-ext** [comment] 2024-05-10 02:52
Oh, this seems expected. It's due to `content-visibility` which is only supported in Firefox 124+
You might want to update.

**Comment by haileyok** [comment] 2024-07-09 01:58
This should be fixed now. Thanks.

**Closed by haileyok** 2024-07-09 01:58 UTC
Labels: bug
