### ISSUE TITLE
Horizontal images for older posts previously uploaded externally to app (1024x512) don't rescale to fit inside post image area on app.

### ISSUE THREAD

**Issue by WriterStat** [bluesky-social/social-app#6814] opened 2024-11-28 11:51 UTC
### Steps to Reproduce

1. go to https://bsky.app/profile/wrtrstat.bsky.social on bluesky
2. scroll down and check previous post's horizontal images.
3. Older post's uploaded horizontal images no longer fit in post's image area/are too big to fit in post area.
4. Cause? Fix?

### What platform(s) does this occur on?

Web (Desktop)

### What version of the app are you using?

Build version: 1.95.0; Bundle info: c9d86de (prod); Bundle date: 24112719; Platform: web; Platform version: undefined

### Additional Information

Is there a new setting to be changed? Thanks, all of my horizontal uploaded images used to fit just fine/correctly inside the post area prior to the last update. Before this last update all my horizontal uploaded images rescaled and fit just fine, but now after the update they are all way too big to fit in the post area. If you visit the page I provided and scroll down you'll see what I mean. Thanks for any help/work arounds. Makes seeing any older post's horizontal images really bad. Appears something unintentionally was over-written/changed. Thanks again. How to set back?

**Comment by WriterStat** [comment] 2024-11-28 11:59
It appears, vertical images in older bluesky posts don't rescale or fit correctly inside posts anymore either. It appears at least for my Bluesky page that for older images and even for newer images on my page that rescaling for images to fit inside post's image area has been lost/broken. Thanks for any pointers/help. Note: all images had fit/displayed correctly and were resized correctly to fit inside post image area on my page prior to last update.

**Comment by gaearon** [comment] 2024-11-28 15:55
Yea, this is the same issue as https://github.com/bluesky-social/social-app/issues/6800.

The change is that we're no longer dynamically resizing images without dimensions. The images on this account don’t have dimensions specified, possibly due to a client you're using. Which client are you using to post?

Dynamically resizing images makes the feed slow for anyone who sees your post — your post would shift all the posts after it as the image loads. So this is why we removed that behavior.

What we *can* do is we can fit them into square boxes instead of cropping them. However, there will be black bars.

**Comment by gaearon** [comment] 2024-11-28 15:57
Going to close as a duplicate of #6800, let's discuss there.

**Closed by gaearon** 2024-11-28 15:57 UTC
Labels: bug

**Comment by WriterStat** [comment] 2024-11-28 17:03
Was using Fedica to schedule them. Trying out Buffer now to schedule to see if makes a difference. Surprisingly, the images I used never shifted. Tbh, no one would see or mind the shift because using a laptop, phone etc... you only see the first 2 or 3 posts, and not the ones below until you scroll, and the shift is fast enough to not be seen on the first 2 or 3.

If you were going to use bars, use the theme color, white for the light theme, black or dark for the dark theme?
