### ISSUE TITLE
Can't create links to certain websites in new posts

### ISSUE THREAD

**Issue by qntm** [bluesky-social/social-app#3032] opened 2024-02-29 00:51 UTC
**To Reproduce**

1. In a desktop web browser (I'm using Microsoft Edge) go to a web page for which a link card could be created, such as https://github.com/bluesky-social.
2. Copy the URL out of the address bar.
3. Go to Bluesky, start creating a new post and paste the copied URL.

In this case, the text pasted into the new post is as follows:

> bluesky-social ([github.com)](https://github.com)

Note the hyperlink. Bluesky then provides a prompt, "Add a link card: [github.com](https://github.com)". Clicking on this prompt adds a link card to https://github.com - which is _not_ the specific page I wanted to link to.

Now try this with a Wikipedia page, such as https://en.wikipedia.org/wiki/Bluesky_(social_network). In this case, the pasted text is simply:

> Bluesky (social network) - Wikipedia

No hyperlink, no URL, no link card prompt, nothing. Linking to Wikipedia doesn't work at all.

**Expected behavior**

If I paste a hyperlink, the pasted text should be the URL and the link card prompt should create a link to that page (as opposed to some other page).

**Screenshots**

![image](https://github.com/bluesky-social/social-app/assets/1735353/d5b2a762-89ab-4a30-af14-98301b561350)

![image](https://github.com/bluesky-social/social-app/assets/1735353/951163f5-1018-48b1-9193-8471cd468edd)

**Details**

 - Platform: Microsoft Edge on Windows

**Additional context**

This is probably happening because of some kind of special clipboard functionality either in Edge or in Bluesky, which replaces the copied string "https://github.com/bluesky-social" with a more advanced object with a special stringified value of some kind. When pasted, the Bluesky post does not receive the pasted URL, it receives the stringified value, which sometimes contains no URL at all, and sometimes contains a short URL for the website's main page, which is the wrong URL.

A workaround is to paste the copied URL into a text editor and then copy and paste it out of the text editor into the new post.

**Comment by Zero3K** [comment] 2024-02-29 01:03
This is a duplicate of https://github.com/bluesky-social/social-app/issues/1321. Please take a look at it for more information.

**Comment by mary-ext** [comment] 2024-02-29 01:46
I'll check in on this in a bit, will have to see if the clipboard data contains some additional metadata

**Comment by Zero3K** [comment] 2024-02-29 01:51
https://stackoverflow.com/questions/67560944/how-to-force-browser-to-paste-url-and-not-page-title-in-edge

**Closed** 2024-06-13 02:37 UTC
Labels: bug
