### ISSUE TITLE
Unable to see other language option 

### ISSUE THREAD

**Issue by jeevikasirwani** [bluesky-social/social-app#3568] opened 2024-04-16 10:00 UTC
**Describe the bug**
unable to see other language option as the font color and background color is white 

**To Reproduce**

1. go to https://bsky.app/
2. belo signup button click on english and menu expands
3. maybe change font color or menu background

**Expected behavior**

list must be visible

**Screenshots**
![Screenshot (267)](https://github.com/bluesky-social/social-app/assets/83456541/f044ba1b-0d92-4375-8b9e-295433f30bb8)

**Comment by mary-ext** [comment] 2024-04-17 01:02
duplicate of https://github.com/bluesky-social/social-app/issues/2963

**Closed** 2024-09-16 20:43 UTC
Labels: bug
