### ISSUE TITLE
Replies to blocked users show up on timeline

### ISSUE THREAD

**Issue by monicaellerose** [bluesky-social/social-app#2025] opened 2023-11-29 06:42 UTC
Default feed view shows when people I follow reply to a blocked post. I see the reply but not the post or person who is either blocked by me or has me blocked

Adding the ability to not see replies to blocked posts would
Make the feeds better and improve user experience 

This would also decrease replies and additional threads on blocked user posts 

Solution: hide replies on feeds if user is blocked or blocks by me

**Comment by pfrazee** [comment] 2023-12-19 20:51
This _should_ be fixed now

**Closed by pfrazee** 2023-12-19 20:51 UTC
Labels: feature-request

**Comment by lsrio** [comment] 2024-04-19 17:50
There seems to be a regression here. These types of replies have been appearing again for a few days now, after having disappeared for months (as intended).

**Comment by monicaellerose** [comment] 2024-04-19 20:36
Same I've also noticed an increase in replies on my timeline to people who I have blocked or have blocked me in the last week or so
