### ISSUE TITLE
Back button does not work in opened Skeets

### ISSUE THREAD

**Issue by diesocke** [bluesky-social/social-app#3856] opened 2024-05-04 08:24 UTC
As of V1.79.0 the system's back button does not work to return from opened skeets. Has this been addressed in V1.80 yet?

### Steps to reproduce the behaviour 

- Open skeet from timeline
- Press system's back button rather than the arrow on top of the screen
-  When having scrolled down, the in-app arrow disappears, so there is only the system's back button visible.

## Expected behaviour

Pressing the system's back button within an opened skeet leads back to timeline. At least the in-app back button should still be visible when scrolling down a skeet.

## System
App version: 1.79.0
OS: Android 14
Device: Samsung Galaxy S24 Ultra

**Comment by mary-ext** [comment] 2024-05-04 08:36
can't reproduce. 1.79.0, Android 13.

the previous issues with back button were caused by menus and dialogs intercepting the back button when they no longer shouldn't be, it's very likely that the same is also happening here, do you remember what you were doing prior to opening the post? does it still happen after force closing the app?

**Comment by diesocke** [comment] 2024-05-04 08:55
Force closing did it. I had swiped the app to close, but it was still running in the background.

**Comment by haileyok** [comment] 2024-05-04 08:56
there's an "all around" fix for this in 1.80. likely in 1.79 it was caused by the gif picker in the composer.

**Comment by haileyok** [comment] 2024-05-05 00:24
Going to close this now but if it keeps happening feel free to reopen!

**Closed by haileyok** 2024-05-05 00:24 UTC
