### ISSUE TITLE
possibility to change  post urls to not need a username to function 

### ISSUE THREAD

**Issue by monicaellerose** [bluesky-social/social-app#1222] opened 2023-08-19 21:49 UTC
right now, if a user changes their username, and shares a post (on a 3rd party site), the post url is broken if it contains the old username

 
sample link
https://bsky.app/profile/bsky.app/post/3k5b7a4fsdd2m

right now: if bsky.app changed the username that link would be broken. 

the solution i would like, and i can't speak to the technical side, 

is regardless of someones username  being changed or not, that an existing link or embed would still work.

on a similar site: domain.com/**username**/status/ then the post id number 

on bluesky:  bluesky/profile/**username**/post/id 
--
when we get the ability to add other usernames or alts, i dont want usernames to be broken, or if people upgrade to a domain in the future,  current links will also be broken

people who change usernames more often, or switch to a domain may not be happy if they understand or realize that links to posts wont work if their name changes, 
i want to tie this kind of too #1085 

getting the post not found error if a post exists and a user changes their name isnt the most effective outcome currently  

![image](https://github.com/bluesky-social/social-app/assets/66647238/8985a7a4-6d92-4e86-a022-ba7f0b37feef)

**Comment by pfrazee** [comment] 2023-08-21 16:07
Thanks for reporting! Going to close this as a duplicate of https://github.com/bluesky-social/social-app/issues/1221#issuecomment-1685126798

**Closed by pfrazee** 2023-08-21 16:07 UTC
Labels: feature-request
