### ISSUE TITLE
Picture Gallery/Revamp Media-Tab

### ISSUE THREAD

**Issue by FlipperLP** [bluesky-social/social-app#1975] opened 2023-11-22 13:33 UTC
**Is your feature request related to a problem? Please describe.**

It is no secret that Twitter and now BlueSky are being used as an art-platform. I frequently watch art and pictures on the platform. But the main issue I'm having is that for each picture there is a username, post-text and likes/comments/repost: They take up a lot of space. Pictures are also not getting displayed horizontally. While that helps pictures to be displayed bigger, it's not idea for browsing them.

**Describe the solution you'd like**

I would be interested in having a grid- or a flow grid-layout to display media more efficiently. It would also help users to find image-posts more easily. I imagine it as a similar concept to Instagram.
For posts that have multiple pictures an artist could select the preview picture, or have them grouped into one of the squares. Another way would be to not make a grid, but rather a post-flow, where pictures take up as much space as they need.
Another cool feature for the artists, would be to hide certain pictures from the gallery to only display art and clean it up from scraps or memes. On the user side, it would still be amazing to have a way to switch them on, if someone wants them displayed.

**Describe alternatives you've considered**

Because Twitter was never really approachable with changes like this, I considered using the API to make my own Website that allows users to view the content as described above and link back to the original post. But… well that is no longer a viable option to me for multiple reasons. Because BlueSky is Open Source and more approachable through GitHub, I thought I could give this a shot, before I try a 2nd time to make my solution happen.

**Additional context**

I'm totally aware that this is most likely not in favor of BlueSky, as the idea is to use it as a short-news platform or for microblogging. But because of Twitter having a lot of artists on their platform, it kinda carries over to BlueSky as they jump ship from Twitter.
This would be a great addition to manage their content better and for consumers to have a better overview of their work.
Even tho I am certain the Media tab is not going to be sacrificed, I would still love to see some switch to turn this feature or dedicate an entire tab to it. (tho I think that would be too much)

**Comment by HeyItsLollie** [comment] 2023-11-23 00:40
For what it's worth, the 3rd-party client Tokimeki (https://tokimeki.blue) displays User Profiles' Media tabs in grid-view by default.

![firefox - 2023-11-23 - 11-05-36](https://github.com/bluesky-social/social-app/assets/30498581/4b9158be-d62b-4d74-8d0a-89e93a779521)

In addition, when using Tokimeki's "Decks" mode, you can choose to display feeds/timelines in both "normal" and "media" views.

![firefox - 2023-11-23 - 11-02-37](https://github.com/bluesky-social/social-app/assets/30498581/938bbf41-a64e-4023-a87a-ceba661a8226)

**Comment by FlipperLP** [comment] 2023-11-24 09:11
Yes! That's amazing! Exactly what I was looking for. But I think it would be better to keep this open for a possible change in the official app. ^^
Tho I will probably use this modified client for now.

**Comment by Zero3K** [comment] 2023-12-10 16:27
Twitter is now using a gallery format for the Media tab of a user. I hope that Bluesky changes it to be the same way soon.

**Comment by pfrazee** [comment] 2023-12-19 20:52
Closing as a duplicate of https://github.com/bluesky-social/social-app/issues/2163, we're +1 to this

**Closed by pfrazee** 2023-12-19 20:52 UTC
Labels: feature-request

**Comment by FlipperLP** [comment] 2023-12-19 20:58
@pfrazee Isn't it better practice merging newer issues into the old one?

**Comment by HeyItsLollie** [comment] 2023-12-19 23:34
Closing duplicates is pretty common practice too, it doesn't really matter which one came first tbh. FWIW, mentioning the related issue by #number ensures that _this_ issue will appear in the related issue's notifications, so any relevant info shared here will still be easy to find later.
![image](https://github.com/bluesky-social/social-app/assets/30498581/a582863c-dc24-4268-8595-e000e8d4ce67)

**Comment by FlipperLP** [comment] 2023-12-20 09:17
> Closing duplicates is pretty common practice too, it doesn't really matter which one came first tbh. FWIW, mentioning the related issue by #number ensures that _this_ issue will appear in the related issue's notifications, so any relevant info shared here will still be easy to find later.
Please read my message again. Issue merging is a very common practice and necessary to keep the conversation of the same issue in one place. But usually you merge _into_ the oldest issue and not to the newest to get the full history and not nest issues into issues. It creates clutter and a false representation of the full timeline. In rare cases it is fine to merge into another issue, if that one has more engagement.
To be fair I was on a short fuse and mad, when I replied to this yesterday as it took me some time and research to put the issue together. Otherwise, I would have let it slide.
