### ISSUE TITLE
Limit how the API can set Link Card information

### ISSUE THREAD

**Issue by sammorrisdesign** [bluesky-social/social-app#950] opened 2023-07-03 15:51 UTC
**Is your feature request related to a problem? Please describe.**

Currently the API allows a developer to customise everything in a Link Card or `app.bsky.embed.external` embed. This is frustrating for a few reasons.

1. In order to post a link via the API, the developer needs to make an additional request to the external URL and fetch everything it needs in order to render a Link Card.
2. Developers could [maliciously modify headlines](https://staging.bsky.app/profile/sammorr.is/post/3jwq3vtdyld2z) to spread misinformation.

**Describe the solution you'd like**
Limit how these embeds are set via the API. Ideally just a URL would be provided to the API. The API could then inflate the URL into the required link card format – similar to how the "add link card" button works on the website and app currently.

**Comment by ansh** [comment] 2023-07-03 17:12
I believe this issue should be raised in the `atproto` repo, if the issue is with the API or the protocol implementaiton.

**Comment by pfrazee** [comment] 2023-07-03 17:15
Yeah depends on how we would want to go at this. The request is to do link-meta fetches on the client instead of the server. We could have the server do it before responding and populate from that, or we could have the client do it on read and essentially use the published card as a hint. After that it's a question of whether the link embed schema needs to change entirely.

Either way we gotta think through how to approach this; it definitely adds more server load to make this change.

**Comment by sammorrisdesign** [comment] 2023-07-07 15:30
@ansh happy to raise a similar issue there if this is an API issue instead

**Comment by ansh** [comment] 2023-09-13 12:30
Closing this in favor of https://github.com/bluesky-social/atproto/discussions/1304 where it is being actively discussed!

**Closed by ansh** 2023-09-13 12:30 UTC
Labels: feature-request
