### ISSUE TITLE
After clicking the 'Translate' button, Bluesky will returns to the home page

### ISSUE THREAD

**Issue by auroursa** [bluesky-social/social-app#6287] opened 2024-11-13 05:56 UTC
### Steps to Reproduce

1. Open a post that needs translation
2. Click the 'Translate' button
3. The browser opens a new tab to load the translation
4. Return to Bluesky's tab, it returns to the home page

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

Windows 11 24H2 + Chrome 131.0.6778.70

### What version of the app are you using?

Build version: 1.93.0; Bundle info: 7731136 (prod); Bundle date: 24110818; Platform: web

**Comment by O4FDev** [comment] 2024-11-13 08:00
Had a quick look - replicated. Going to have a look into fixing :)

**Comment by surfdude29** [comment] 2024-11-20 06:00
@auroursa @O4FDev Are either of you able to reproduce this in 1.94? I was previously seeing this on iOS, but now it's working fine for me.

**Comment by auroursa** [comment] 2024-11-20 06:14
> @auroursa @O4FDev Are either of you able to reproduce this in 1.94? I was previously seeing this on iOS, but now it's working fine for me.

Yes, unfortunately, I am still able to reproduce this issue in 1.94, whether on Web, Android, or iOS.

Strangely, I can’t always reproduce it on iOS. It seems that under certain conditions, iOS handles the translation properly without returning to the homepage. But on the Web, though, I can almost reproduce the issue 100% of the time. I’ve tried resetting all settings, switching the language to English, and changing browsers (from Chrome to Firefox).

**Comment by surfdude29** [comment] 2024-11-20 07:30
I just tried in Safari on my iPad, and yep, it's definitely still an issue in 1.94 🙃 Maybe I just got lucky when it didn't happen in the iOS app?

> I'm kind of afraid to click the translate button right now because I'm worried it will take me back to the homepage and I won't be able to find the post I was just looking at.

It's annoying to have to do because it's an extra click/tap, but as a workaround, does it happen when you use Translate from the post context menu? I've never had it happen when using that.

**Comment by O4FDev** [comment] 2024-11-20 08:33
Hahah... yeah let's not ignore the translate button 😆. 

I'm not quite sure how to get my PR reviewed and merged that fixes this, just hoping the team sees this before it gets too far back into the pages

**Comment by auroursa** [comment] 2024-11-20 08:37
> Hahah... yeah let's not ignore the translate button 😆.
> 
> I'm not quite sure how to get my PR reviewed and merged that fixes this, just hoping the team sees this before it gets too far back into the pages

Don't worry, things will be resolved. They just have many other important things to take care of.

**Closed** 2024-11-23 17:25 UTC
Labels: bug
