### ISSUE TITLE
Profile header covers over back button on mobile

### ISSUE THREAD

**Issue by electricduck** [bluesky-social/social-app#5752] opened 2024-10-14 17:38 UTC
### Steps to Reproduce

1. Open mobile app, or resize browser to disable mobile version of website
2. Go onto a profile (`https://bsky.app/profile/<username>`)
3. Notice the back button is very briefly displayed before the header loads in and covers it

#### Desktop

![image](https://github.com/user-attachments/assets/1645e951-628e-4ce9-bdda-bee9c7cd83c0)

#### Mobile

![Screenshot_20241014-183441](https://github.com/user-attachments/assets/055e87a9-8584-42e1-af65-12ee72c802f7)

### What platform(s) does this occur on?

iOS, Android, Web (Mobile)

### What version of the app are you using?

1.92.1.355 6550029 (prod)

**Comment by Rohit3523** [comment] 2024-11-02 21:02
I can see the back button on the header, Please try upgrading the app and report it back if you are still facing the same issue with your device information

**Comment by yudistiraashadi** [comment] 2024-11-03 05:19
can confirm no back button for Android and mobile screen on chrome 
![image](https://github.com/user-attachments/assets/2e1dbe78-3dc6-4761-b884-3a96dfdbf998)

**Comment by Rohit3523** [comment] 2024-11-03 09:05
@yudistiraashadi can you provide your device detail because back button is currently visible for me on multiple emulators

**Comment by yudistiraashadi** [comment] 2024-11-03 09:27
@Rohit3523 
I'm using:

- Bluesky version 1.92.1 Android App
- Samsung A55 - One UI verson 6.1
- Android 14
- Kernel version: 6.1.43-android14-11

Let me know if you need more information

**Comment by Rohit3523** [comment] 2024-11-03 09:32
Can you please provide the steps to reproduce this bug because i am unable to reproduce it ;-;

**Comment by Rohit3523** [comment] 2024-11-03 09:37
The back button is only missing on the Android Chrome version, not in the app.

**Comment by yudistiraashadi** [comment] 2024-11-03 10:06
Here I tried to reinstall the app. The first video is the prof I reinstalled it. The second video shows the back button initally exist, but got covered by the header image

https://github.com/user-attachments/assets/44183d3c-bac6-46c7-84d0-040d4740263b

https://github.com/user-attachments/assets/2aa6f5ab-6a45-4894-a53e-518fa8111967

**Comment by Rohit3523** [comment] 2024-11-03 11:02
Just checked this issue is already fixed (PR is already merged)

https://github.com/bluesky-social/social-app/pull/5748

**Closed** 2024-11-04 20:32 UTC
Labels: bug
