### ISSUE TITLE
When I open the posting UI, it displays gray-colored boxes behind the posting interface.

### ISSUE THREAD

**Issue by cosmostellar** [bluesky-social/social-app#4813] opened 2024-07-23 02:12 UTC
**Describe the bug**
With the posting UI opened, it displays gray boxes in both side sections.
At least on macOS, it seems like they're only visible on Firefox. I haven't checked it on other systems.

**To Reproduce**
- Open the posting UI on Firefox.

**Screenshots**
Safari:
<img width="866" alt="safari" src="https://github.com/user-attachments/assets/ea5e62f6-99bf-4d71-b56b-a9b6ad43b1b2">
Firefox:
<img width="857" alt="firefox" src="https://github.com/user-attachments/assets/a2f154bf-76da-46e7-b2c8-e031c6170676">

**Details**
 - Platform: macOS
 - Platform version: 14.5
 - App version: 1.88.0

**Comment by oracularhades** [comment] 2024-07-25 10:19
I can't reproduce, do you have any extensions installed? Otherwise, you may have an accessibility setting, or your display driver / colour profile is broken.

**Comment by cosmostellar** [comment] 2024-07-25 11:30
I just realized it only happens on my external monitor with some specific color profiles. I can't reproduce it on my MacBook monitor either. I wonder why though.

**Comment by cosmostellar** [comment] 2024-07-25 11:32
It's probably the color profile. Even on the external monitor, I can't reproduce it with sRGB profile. Should I close the issue?

**Comment by oracularhades** [comment] 2024-07-26 00:39
Yes to closing, display drivers / color issues are out of Bluesky's control :)

**Closed** 2024-07-26 01:05 UTC
Labels: bug
