### ISSUE TITLE
Report Post Modal: Submit button off-screen on some screens

### ISSUE THREAD

**Issue by jcsalterego** [bluesky-social/social-app#901] opened 2023-06-24 20:27 UTC
**Describe the bug**

The button to submit isn't viewable or accessible after selecting a reason for Report Post.

**To Reproduce**

On Android:

1. Report Post
2. Select reason

**Expected behavior**

The submit button is viewable and accessible.

**Screenshots**
![bafkreiacf6r63dk4loq4mvo32k44cadd2m44zvemvbsx2lknz3x5mevla4](https://github.com/bluesky-social/social-app/assets/30475/e87ad943-e32a-4638-8c23-cbb014557f73)

**Details**

 - Platform: Android
 - Platform version:
 - App version:

**Additional context**

As reported by @juliaferraioli [https://bsky.app/profile/juliaferraioli.com/post/3jywirwehqo2q](https://bsky.app/profile/juliaferraioli.com/post/3jywirwehqo2q)

**Comment by pfrazee** [comment] 2023-06-26 15:23
I'll dig into this!

**Comment by juliaferraioli** [comment] 2023-06-26 16:25
I have heard that this also affects the iOS client, but I don't have access to an iPhone to confirm.

**Comment by alimony** [comment] 2023-06-26 16:28
I can't reproduce this on an iPhone 11 running iOS 16.4.1.

**Comment by jcsalterego** [comment] 2023-06-26 16:30
> I can't reproduce this on an iPhone 11 running iOS 16.4.1.

Have you tried bumping up the OS font size in the system settings? This may only happen on smaller form factors as well.

**Comment by alimony** [comment] 2023-06-26 16:33
> > I can't reproduce this on an iPhone 11 running iOS 16.4.1.
> 
> @alimony Have you tried bumping up the OS font size in the system settings? This may only happen on smaller form factors as well.

Ah, yes! I can confirm this breaks on larger font sizes on iOS. Going up one step from default font size cuts the button in half, above that it disappears completely.

**Comment by jcsalterego** [comment] 2023-06-26 16:34
@alimony thx!

**Comment by juliaferraioli** [comment] 2023-06-26 16:49
Yes, to clarify, the issue is an accessibility one where larger than default font sizes result in a variety of scaling issues within the UI. I highly encourage testing at all supported text size settings for all features.

**Comment by maique** [comment] 2023-06-27 18:22
I have this behavior, iPhone 13 Pro, latest non-beta iOS version.

**Comment by pfrazee** [comment] 2023-07-03 15:28
This should be fixed now, let me know if it's still happening!

**Closed by pfrazee** 2023-07-03 15:28 UTC
Labels: bug, x:planned

**Comment by juliaferraioli** [comment] 2023-07-03 15:36
Just to confirm, this is just fixing the report dialogue, correct? Are the other text scaling issues tracked elsewhere?

**Comment by pfrazee** [comment] 2023-07-03 16:01
@juliaferraioli correct -- no other issue open at the moment. I did a full pass on the app and wasn't able to identify any other issues but entirely possible there are

**Comment by juliaferraioli** [comment] 2023-07-03 16:37
Opened another issue: https://github.com/bluesky-social/social-app/issues/952
