### ISSUE TITLE
Bug: Scrolling Home jumps erratically on Firefox 

### ISSUE THREAD

**Issue by Gazzoo-byte** [bluesky-social/social-app#1752] opened 2023-10-14 19:00 UTC
As above, scrolling through the Home timeline jumps erratically as posts are (un?)loaded, doesn't appear to affect Chromium based browsers

OS: Win 11
Firefox ver: 118.0.2

**Comment by bnewbold** [comment] 2023-10-26 00:29
I'm not sure if this is a dupe of previous "wild scroll" issue, or perhaps https://github.com/bluesky-social/social-app/issues/1418

**Comment by pfrazee** [comment] 2023-12-19 21:21
This will hopefully get fixed with an update @gaearon is working on

**Comment by mschwendener** [comment] 2023-12-30 21:46
I see this for the first time today (1.62.0), while scrolling the Birds feed https://bsky.app/profile/did:plc:ffkgesg3jsv2j7aagkzrtcvt/feed/aaagllxbcbsje in Firefox on MacBook

**Comment by haileyok** [comment] 2024-07-09 01:54
Should be fixed up now.

**Closed by haileyok** 2024-07-09 01:54 UTC
Labels: bug, x:planned
