### ISSUE TITLE
Favicon changes after clicking on a link on iPad

### ISSUE THREAD

**Issue by bernd289** [bluesky-social/social-app#1709] opened 2023-10-17 19:36 UTC
On iPad the bsky Favicon changes to the one of the last Website I clicked a link while scrolling through my timeline.

See attached examples.

![image](https://github.com/bluesky-social/social-app/assets/3106989/fa137245-164f-4378-ae81-e73c83894b6b)
![image](https://github.com/bluesky-social/social-app/assets/3106989/33e0f875-47c3-4a4f-905e-8e1fddb0cdf4)
![image](https://github.com/bluesky-social/social-app/assets/3106989/fb43503b-286b-4842-aaa9-49e1873f1992)

I'm using Safari on an iPad Pro 11 with iPadOS 17.0.3

**Comment by ansh** [comment] 2023-10-19 20:12
This is most likely a bug in iPadOS since our favicon support is not browser-specific and this error cannot be reproduced by me on any desktop browsers. 

For now, I am closing this issue but feel free to comment here if this issue is reproducible on other platforms as well.

**Closed by ansh** 2023-10-19 20:12 UTC
