### ISSUE TITLE
Username input broken on edge browser

### ISSUE THREAD

**Issue by Ajaymaurya1008** [bluesky-social/social-app#6806] opened 2024-11-28 08:49 UTC
### Steps to Reproduce

Open microsoft edge browser
open https://bsky.app
you won't be to type username
![image](https://github.com/user-attachments/assets/5092d1cc-04bb-44f7-8232-4d09e590b20d)

### What platform(s) does this occur on?

Web (Desktop)

### Device Info

Windows 11

### What version of the app are you using?

Web app latest

**Comment by khuddite** [comment] 2024-12-02 02:18
![image](https://github.com/user-attachments/assets/9b81d320-59ca-4141-828a-3a99fe16b1c9)

I am not able to reproduce the issue on Microsoft Edge for Windows. @Ajaymaurya1008 Let me know if you are still able to reproduce the issue on the latest build.

**Comment by Ajaymaurya1008** [comment] 2024-12-02 04:23
Hey, it got fixed, actually it wasn't because of the browser but due to some extension 
On the Incognito tab, it works fine

**Comment by khuddite** [comment] 2024-12-02 13:28
@Ajaymaurya1008 Alright, would you mind closing out the ticket then? Thanks

**Closed** 2024-12-02 14:22 UTC
Labels: bug
