### ISSUE TITLE
Follower/Following Counts round up on iOS

### ISSUE THREAD

**Issue by hipstersmoothie** [bluesky-social/social-app#6194] opened 2024-11-09 22:43 UTC
### Steps to Reproduce

On some profiles if you view them on web vs iOS you'll notice that on web they round down all the time (ex: 7199 => 7.1k) but on iOS it seems like it goes to "nearest" (ex: 7199 => 7.2k)

The problem I think is that in `//social-app/src/view/com/util/numeric/format.ts` the rounding mode is set to `trunc` when it should be set to `floor`.

This works on web, I wasn't able to test on iOS cause I couldn't get the simulator going

### What platform(s) does this occur on?

iOS

### What version of the app are you using?

1.93

**Comment by mary-ext** [comment] 2024-11-10 05:15
Duplicate of https://github.com/bluesky-social/social-app/issues/5538

**Closed** 2024-11-10 07:27 UTC
Labels: bug
