### ISSUE TITLE
Unable to Scroll on iOS App when fingers starts on pfp, feed tab, or bio url.

### ISSUE THREAD

**Issue by richardziegler** [bluesky-social/social-app#2477] opened 2024-01-10 21:37 UTC
**Describe the bug**
When on a user's profile and you try to scroll down: If your finger starts on a profile picture, a hyperlink in a user's bio, or one of the tabs to select which feed (posts, replies, media, likes) it does not scroll.

**To Reproduce**

1. Go to any user's profile on the iOS app.

2. Try to scroll down with your finger starting on a profile picture, bio hyperlink, or feed tab.

**Expected behavior**

I expect the normal scrolling behavior of the page scrolling down. 

**Screenshots**

Using accessibility features to showcase where the user's finger is starting from.

https://github.com/bluesky-social/social-app/assets/37094831/2baf1af7-209a-4166-b042-02d3919e6fa0

**Details**

 - Platform: iOS
 - Platform version: iOS 17.2.1 on iPhone 15 Pro Max
 - App version: 1.63.0 (1)

**Additional context**

None to add at this time.

**Comment by pfrazee** [comment] 2024-01-10 22:50
Thanks for reporting! This is a duplicate of https://github.com/bluesky-social/social-app/issues/2220 and is on our TODOs

**Closed by pfrazee** 2024-01-10 22:50 UTC
Labels: bug
