### ISSUE TITLE
[Bluesky Web] Feed scrolling issue on Firefox

### ISSUE THREAD

**Issue by edueocara27** [bluesky-social/social-app#1418] opened 2023-09-08 15:45 UTC
**Describe the bug**

The scrolling of feeds on Bluesky is glitchy on my Firefox. Basically if I keep scrolling down the posts, problems start to appear with scrolling getting jumpy, jumping up despite scrolling down and also jumping down, skipping posts. I have this problem even scrolling slowly or scrolling up. Only Firefox has this problem. In any Chromium browser, I basically use the same scrolling speed without any problems.

**To Reproduce**

1. Open Mozila Firefox
2. Type about:config on adress bar and change the following settings: general.smoothScroll.msdPhysics.enabled (set to true) and mousewheel.default.delta_multiplier_y (set to 300)
3. Go to bsky.app
4. Scroll down the posts on any feed

**Expected behavior**

The scrolling of posts remained smooth and constant, without skipping posts or wanting to scroll up

**Details**

 - Platform: Mozila Firefox 117.0, Windows 11
 - App version: Bluesky Web 1.49.0

**Additional context**

As I made clear in ''Step to reproduce'', I use advanced settings in Firefox to improve scrolling i.e. make scrolling faster and smoother. If I use Firefox's default scrolling, this problem doesn't occur.

I want to clarify that I had been using Bluesky on Firefox with these settings without any problems until the beginning of August. Since then, just from one day to the next, this problem appears, I don't know if it was triggered by a Firefox update or a Bluesky update.

**Comment by ansh** [comment] 2023-09-13 12:11
If you are able to use the same higher scrolling speed in any Chromium browser, it is likely that this issue is due to a Firefox update. 

You are currently on Firefox 117.0

Could you try it with an older version of Firefox? [According to the Firefox website](https://www.mozilla.org/en-US/firefox/115.0/releasenotes/) version 115.0 came out sometime in July which might be a good version to test.

**Comment by brawaru** [comment] 2023-09-19 04:38
There are somewhat similar issues in Chrome (Edge) if you are using middle mouse scroll, but they're less drastic. The feed can just start blinking, jump somewhere else, and such, but mostly the tab is actually just freezing (lol). In Firefox it's much much more visible, perhaps Firefox is just slower to update DOM tree or doesn't render anything when JavaScript thread is busy, or allows scrolling even when scroll event is making the JS thread busy. I have no clue at all.

One thing that somewhat helps in Firefox is opening any feed through My feeds » [Gear icon] » [Any feed], because in that mode there's no navigation bar at the top that keeps showing and hiding in a loop and that reduces the amount of layout shifts, and thus makes feed less jumpy.

**Comment by ansh** [comment] 2023-09-21 07:51
I'll be closing this now as it seems to be a Firefox issue.

**Closed by ansh** 2023-09-21 07:51 UTC
Labels: bug, x:discussing

**Comment by brawaru** [comment] 2023-09-21 12:23
@ansh is there any chance reproducers/maintainers at Webcompat and Firefox can get invite codes to create accounts on Bluesky? I'm unfortunately don't have any codes.

**Comment by edueocara27** [comment] 2023-09-21 14:25
> @ansh is there any chance reproducers/maintainers at Webcompat and Firefox can get invite codes to create accounts on Bluesky? See the above [issue](https://github.com/webcompat/web-bugs/issues/127371). I unfortunately don't have any codes.
> 
> ~I'll check with them for which way they'd like to receive them because sending them here will lead them to immediately hoovered by bots, most likely.~ [They told](https://github.com/webcompat/web-bugs/issues/127371#issuecomment-1729586065) to send the invite to [rbucata@mozilla.com](mailto:rbucata@mozilla.com).

I sent a code to the email
